CREATE TABLE IF NOT EXISTS players (
  id BIGSERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  country_code TEXT,
  gold BIGINT NOT NULL DEFAULT 10000,
  food BIGINT NOT NULL DEFAULT 50000,
  oil BIGINT NOT NULL DEFAULT 20000,
  army BIGINT NOT NULL DEFAULT 1000,
  level INT NOT NULL DEFAULT 1,
  xp BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_active TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS countries (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  owner_id BIGINT REFERENCES players(id) ON DELETE SET NULL,
  power BIGINT NOT NULL DEFAULT 1000,
  population BIGINT NOT NULL DEFAULT 1000000,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alliances (
  id BIGSERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  tag TEXT UNIQUE NOT NULL,
  leader_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alliance_members (
  alliance_id BIGINT NOT NULL REFERENCES alliances(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (alliance_id, player_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGSERIAL PRIMARY KEY,
  player_id BIGINT REFERENCES players(id) ON DELETE SET NULL,
  username TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS battles (
  id BIGSERIAL PRIMARY KEY,
  attacker_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  defender_id BIGINT REFERENCES players(id) ON DELETE SET NULL,
  country_code TEXT NOT NULL REFERENCES countries(code),
  attacker_loss BIGINT NOT NULL,
  defender_loss BIGINT NOT NULL,
  result TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_created_at ON chat_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_players_active ON players(last_active);
